### ISSUE TITLE
 Undefined constant "MYSQLI_OPT_CONNECT_TIMEOUT" from PHP8.1 and newer

### ISSUE THREAD

**Issue by Pitcher66** [SergeyTsalkov/meekrodb#100]
MeekroDB gets an error on PHP8.1 and newer cause constant "MYSQLI_OPT_CONNECT_TIMEOUT" seems to be depreciated.

**Comment by SergeyTsalkov** [comment]
Sounds like you didn't install the mysqli extension for PHP. On Ubuntu that's the php8.1-mysql package, but your particular situation might be different.

I'll make an update so it shows a more sensible error message in this case.
