### ISSUE TITLE
Visual Studio Code with Intelephense Emit Warning

### ISSUE THREAD

**Issue by tohizma** [SergeyTsalkov/meekrodb#102]
Latest update of Meekrodb (v2.5) emit warning in VSC Editor (with Intelephense extension) for almost every meekrodb methods, example message : ```Non static method 'insert' should not be called statically.intelephense(1036)```

The cause of problem is comment annotation above ```class DB {```

```
/**
 * @link https://meekro.com/docs/retrieving-data.html Retrieving Data
 * 
 * @method static query(string $query, ...$parameters)
 * @method static queryFirstRow(string $query, ...$parameters)
 * @method static queryFirstField(string $query, ...$parameters)
 * @method static queryFirstList(string $query, ...$parameters)
 * @method static queryFirstColumn(string $query, ...$parameters)
 * @method static queryFullColumns(string $query, ...$parameters)
 * 
 * @link https://meekro.com/docs/altering-data.html Altering Data
 * 
 * @method static insert(string $table_name, array $data, ...$parameters)
 * @method static int insertId()
 * @method static insertIgnore(string $table_name, array $data, ...$parameters)
 * @method static insertUpdate(string $table_name, array $data, ...$parameters)
 * @method static replace(string $table_name, array $data, ...$parameters)
 * @method static update(string $table_name, array $data, ...$parameters)
 * @method static delete(string $table_name, ...$parameters)
 * @method static int affectedRows()
 * 
 * @link https://meekro.com/docs/transactions.html Transactions
 * 
 * @method static startTransaction()
 * @method static commit()
 * @method static rollback()
 * 
 * @link https://meekro.com/docs/hooks.html
 * 
 * @method static int addHook(string $hook_type, callable $fn)
 * @method static removeHook(string $hook_type, int $hook_id)
 * @method static removeHooks(string $hook_type)
 * 
 * @link https://meekro.com/docs/misc-methods.html Misc Methods and Variables
 * 
 * @method static useDB(string $database_name)
 * @method static array tableList(?string $database_name = null)
 * @method static array columnList(string $table_name)
 * @method static disconnect()
 * @method static mysqli get()
 * @method static mixed lastQuery()
 * @method static string parse(string $query, ...$parameters)
 */
```

When I remove that annotation doc block, warning is disappear, maybe VSC and Intelephense assume ```/** ...*/``` as class/function's docblock which doesn't match with meekrodb function declaration (no static in function declaration)

VS Code v1.82.2
Intelephense v1.9.5

**Comment by tohizma** [comment]
The quick fix is use only single asterisk for main class doc comment ```/* ....... */```

**Comment by SergeyTsalkov** [comment]
Why is this a bug in MeekroDB, and not in Intelephense? The phpdoc block above the DB class describes static methods contained by the DB class. The DB class *does* implement static methods such as query() and insert(). As far as I know, this is how you're supposed to properly use phpdoc comments. Is there some phpdoc.org documentation you can point to, to convince me that I'm wrong?

**Comment by tohizma** [comment]
The syntax for @method annotation expect return type
[https://docs.phpdoc.org/guide/references/phpdoc/tags/method.html#method](url)

Intelephense already support class method annotation
[https://github.com/bmewburn/vscode-intelephense/issues/480](url)

If I modify to add return type, everything works well
```@method static insert(string $table_name, array $data, ...$parameters)```
changed to
```@method static int insert(string $table_name, array $data, ...$parameters)```

**Comment by SergeyTsalkov** [comment]
Ok, thank you for that explanation! I'll correct this soon.

**Comment by tohizma** [comment]
Thank you for your great work

**Comment by nan4k7** [comment]
Hello, any idea when this commit will go to a new version?

**Comment by SergeyTsalkov** [comment]
Thanks for the reminder, I just put out a release now.
