### ISSUE TITLE
Using LIKE in a query

### ISSUE THREAD

**Issue by danielscsc** [SergeyTsalkov/meekrodb#103]
Hi there.  Thank you for this wonderful library.

I'm having a hard time accomplishing the following:

```SQL
SELECT * FROM table WHERE column LIKE 'ABC%';
```

How would I do that in Meekro, where ABC is a %s

Based on the docs, I was trying this:
```PHP
DB::query("SELECT * FROM table WHERE column LIKE %s%%", $stringValue)
```
but it wasn't working.

Thanks again.

EDIT:
This works for now:
```PHP
DB::query("SELECT * FROM table WHERE column LIKE %s", $stringValue.'%');
```

If there's another way I should be doing it please let me know, otherwise feel free to close the issue :)

**Comment by SergeyTsalkov** [comment]
You got it.
