### ISSUE TITLE
Setting Encoding/Charset not via DSN

### ISSUE THREAD

**Issue by danielscsc** [SergeyTsalkov/meekrodb#105]
I think, based on reading the code, that if someone provides a dsn, yet omits the `charset` part of the dsn, and supplies it via the old way (DB::encoding), it gets ignored.

Current Meekro code:
```PHP
  public function get() {
    $pdo = $this->internal_pdo;
    
    if (!($pdo instanceof PDO)) {
      if (! $this->dsn) {
        ...
        if ($this->encoding) $dsn['charset'] = $this->encoding; // we only do this if dsn isnt passed
        ...
        $this->dsn = 'mysql:' . implode(';', $dsn_parts);
      }

      list($this->db_type) = explode(':', $this->dsn); // p.s. neat way of avoiding [0]
 
    ...
    return $pdo;
  }
```

For example, I used to have code like this:

```PHP
  MeekroDB::$user = env('DB_USER');
  MeekroDB::$password = env('DB_PASS');
  MeekroDB::$dbName = env('DB_NAME');
  MeekroDB::$encoding = 'utf8mb4';
```

and changed it to:
```PHP
  MeekroDB::$dsn = 'mysql:host=localhost;dbname='.env('DB_NAME');
  MeekroDB::$user = env('DB_USER');
  MeekroDB::$password = env('DB_PASS');
  MeekroDB::$encoding = 'utf8mb4';
```

But that won't work.  I'd need to change it to:
```PHP
  MeekroDB::$dsn = 'mysql:host=localhost;charset=utf8mb4;dbname='.env('DB_NAME');
  MeekroDB::$user = env('DB_USER');
  MeekroDB::$password = env('DB_PASS');
```

Not sure I would categorize this as a bug, but I would suggest making it clear in the documentation that if you are supplying a dsn string, and want to specify encoding, you must include it in the dsn.  (Or update the meekro code to use the user-supplied encoding if it exists)

Thanks for this amazing tool!

**Comment by SergeyTsalkov** [comment]
Hey, thanks for testing out the new release! So what happened is that these variables are now considered deprecated: $host, $port, $socket, $dbName, $encoding. You'll notice that none of them are even mentioned in the documentation anymore, and the proper way to configure things is to set the $dsn. However, to maintain backwards compatibility (and make v3 as much of a drop-in replacement as possible) I made it so if you don't specify $dsn it will use the old variables.

In your case, you can just go back to what you did originally and it'll work fine:

```php
DB::$user = env('DB_USER');
DB::$password = env('DB_PASS');
DB::$dbName = env('DB_NAME');
DB::$encoding = 'utf8mb4';
```
