### ISSUE TITLE
FEAT: Warn About Mismatch Between Number of Placeholders and Parameters

### ISSUE THREAD

**Issue by danielscsc** [SergeyTsalkov/meekrodb#108]
I have encountered an issue (or possibly a feature request) where Meekro allows the execution of queries even when the number of parameters passed does not match the number of placeholders in the SQL statement.

#### Example:
```php
DB::query(
  "UPDATE table SET col=NULL WHERE id=%i AND col2=%i",
  $value1,
  $value2,
  $value3
);
```

In the above example, the query runs successfully with `id` being assigned `$value1` and `col2` being assigned `$value2`. The third parameter, `$value3`, is ignored.

#### Expected Behavior:
I would expect the library to throw an error or exception indicating that the number of parameters passed does not match the number of placeholders in the query. This would help prevent potential bugs and ensure that queries are constructed and executed as intended.

Please let me know if this behavior is intentional or if there are plans to enforce stricter parameter validation.

P.S.  I could have given a simpler example, but I'm using the one that caused me to notice the issue 😉  I had copied the query from a different section of the code where I actually was setting `col` to `$value1`, unlike this code where I was just `null`'ing it, but forgot to drop the first param (`$value1`).
P.P.S. Thanks for this wonderful library!

EDIT:
Did a quick look into the code, and came up with the following.  You can probably optimize/improve it (and the exception message), as well as handle edge cases (ensure is countable or returns 0).:

```PHP
  function parse($query) {
    $args = func_get_args();
    array_shift($args);

	// <snip>

    if (count($args) != count($ParsedQuery->params)) {
      throw new MeekroDBException('Mismatch params count');
    }

    return $ParsedQuery;
  }
```

**Comment by SergeyTsalkov** [comment]
I think this is a good idea, and I'll add it soon. Unfortunately it's a bit more subtle than your suggested implementation. The `$ParsedQuery` params are the ones that will go into the PDO prepared statement, so there could be a different number of them than you'd expect. For example:

```php
DB::query("SELECT email FROM accounts WHERE id IN %li", array(3,4,5));
```

In that case `count($args)` will return 1 and `count($ParsedQuery->params)` will return 3.

But it's okay-- I know how to do it and will get around to it soon! 😃
