### ISSUE TITLE
count() function does not exist 

### ISSUE THREAD

**Issue by ponasromas** [SergeyTsalkov/meekrodb#109]
Upgraded to recent version of meekro and getting this:

`PHP Fatal error:  Uncaught MeekroDBException: MeekroDB does not have a method called count in /vendor/sergeytsalkov/meekrodb/db.class.php:109`

If there is no count(), how can I count result?

**Comment by danhaber** [comment]
You didn't post what your code looks like, but based on the error it seems like you're trying to call a method "count" **of** Meekro.  That won't work.  If you are trying to get the count of results, you should do something like:

```PHP
$results = DB::query("SELECT * FROM table");
$count = count($results);
```

**Comment by ponasromas** [comment]
Yea, I just blindly upgraded from 2.5.1 to 3.x :) and boom. Just downgraded. Thank you for quick reply!

**Comment by danhaber** [comment]
> Yea, I just blindly upgraded from 2.5.1 to 3.x :) and boom. Just downgraded. Thank you for quick reply!

Looked at the docs for 2.5.1, seems like it was marked for deprecation:
https://github.com/SergeyTsalkov/meekrodb/blob/v2.5.1/db.class.php#L379
