### ISSUE TITLE
PDO::__construct(): Argument #4 ($options) must be of type ?array, string given

### ISSUE THREAD

**Issue by kangarko** [SergeyTsalkov/meekrodb#110]
After updating to v3 I am unable to use the library due to the following issue:

```
Code:

0: PDO::__construct(): Argument #4 ($options) must be of type ?array, string given

Location:

/home/matej/web/mzda.mineacademy.org/public_html/vendor/sergeytsalkov/meekrodb/db.class.php#208
```

Running on PHP 8.3.13. 

The issue points to this line in your db class:

`$pdo = new PDO($this->dsn, $this->user, $this->password, $this->connect_options);`

Looks like the $this->connect_options needs to be a string but it is an array, if I am understanding it properly. I am unsure whether this is coming from my setup or I need to change something after the upgrade, any help would be appreciated.

Matej

**Comment by SergeyTsalkov** [comment]
How exactly are you constructing the MeekroDB instance, or setting its options initially?

**Comment by SergeyTsalkov** [comment]
So the "new MeekroDB" line is different for v3. That's the only breaking change, everything else should work the same. You want something like:

```php
$dsn = 'mysql:host=localhost;dbname=mydatabase';
$db = new MeekroDB($dsn, $user, $password);
```

This is documented here: https://meekro.com/docs/static-vs-object.html

That should resolve your problem, but I'm leaving this ticket open to remind myself to add an FAQ entry or something.

Also, the way you're querying the database is not ideal-- concatenating strings opens you up to bugs and vulnerabilities if that function is ever used with user-supplied timestamps. A better way would be:

```php
$this->database->query('SELECT * FROM %b WHERE date BETWEEN %s and %s', $this->tableName, $startTimestamp, $endTimestamp);
```

**Comment by kangarko** [comment]
Thanks, works now! I also appreciate your advice regarding queries, thanks for the tip!
