### ISSUE TITLE
Changing PDO::ATTR_STRINGIFY_FETCHES

### ISSUE THREAD

**Issue by danhaber** [SergeyTsalkov/meekrodb#112]
PHP Version: 8.1.x
MySQL Version: 8.40
Meekro Version: 3.1.3

Is it OK if I set to set this to false (which is the PHP PDO default, although there were changes that affected this in general since PHP 8.1*)?  I see Meekro sets this to true explicitly by default (in [this commit](https://github.com/SergeyTsalkov/meekrodb/commit/f54647257d283232f5cbd274ce2ac5ecf211e8e0)), and I'm wondering if that's being relied upon elsewhere in the Meekro code.

Thanks again for this great library! 

* See [1](https://www.php.net/manual/en/migration81.incompatible.php#migration81.incompatible.pdo), [2](https://github.com/php/php-src/pull/11622), [3](https://externals.io/message/113294).

**Comment by SergeyTsalkov** [comment]
I'm pretty sure it's okay to change it. It's not tested in that mode, but I don't see any reason why it should break. The reason for this default is to maintain backwards compatibility with the mysqli-based MeekroDB 2.*.

If there are any problems using it that way, feel free to open bug reports and I'll see what can be done.
