### ISSUE TITLE
Not possible to query for NULL value?

### ISSUE THREAD

**Issue by col000r** [SergeyTsalkov/meekrodb#23]
Is there a way I can handle a case like this, where $parent_id could be any number or NULL?

``` php
function FindChildren($parent_id) {
     $results = DB::query("SELECT item_id FROM items WHERE parent_item_id=%?", $parent_id);
}
```

I'm doing it the following way way now, but I was wondering if there was a way to make this happen automagically...

``` php
if($parent_id == null) $results = DB::query("SELECT item_id FROM items WHERE parent_item_id IS NULL");
else $results = DB::query("SELECT item_id FROM items WHERE parent_item_id=%i", $parent_id);
```

PS: love meekrodb a lot!

**Comment by asafnevo** [comment]
@SergeyTsalkov couldn't you create a new variable type (like %n, representing nullable value) ?
if %n parameter is null just put null, if not put the value in the parameter?

**Comment by asafnevo** [comment]
Well my problem is more on the stored procedure side.
I have a stored procedure in which some of the values i'm sending needs to be null instead of quotes, according to the php value

**Comment by spidfire** [comment]
And you can't just use something like `DB::query("SELECT * FROM users WHERE test IS NULL");` ?

**Comment by asafnevo** [comment]
Not really. I have a SP which execute:
Call SP(param1,param1,param3,param4).
The thing is that param2 for instance could either a string or NULL, param3 could be int or NULL.

Anyhow I solved by creating my query in a different function according to the param value, but I thought that creating a Meekrodb variable type like nullable int or nullable string could be a generic solution. That way if the string is null, it could just output NULL. same thing with int

**Comment by spidfire** [comment]
In that case you could add ->
in db.class.php
add on line 440: `$this->param_char . 'ns'  // nullable string`
add on line 615: `else ($type == 'ns') $result = is_null($arg) ? "NULL" : $this->escape($arg);`

Maybe something like this? (not sure if this works or if its the right way to go)

**Comment by asafnevo** [comment]
Yeah I solved it for now,
Just wanted to suggest that maybe that was you could add a generic support for that in your library
