### ISSUE TITLE
Date format not working

### ISSUE THREAD

**Issue by 123BDJR** [SergeyTsalkov/meekrodb#27]
When i use a query like this:

    $result = DB::query("SELECT t3.name as module,t2.firstname as user,t1.module_identifier,t1.field,t1.old_value,t1.new_value,DATE_FORMAT(t1.timestamp,'%d-%d-%Y %T') as timestamp FROM log t1 LEFT JOIN user t2 ON t2.id = t1.user_id LEFT JOIN module t3 ON t3.id = t1.module_id WHERE %l ORDER BY t1.timestamp ASC", $where);

MeekroDB processes the DATE_FORMAT settings as variables because of the % markup. Is there a workaround for this?

**Comment by SergeyTsalkov** [comment]
See the question about DATE_FORMAT at: http://www.meekro.com/help.php
