### ISSUE TITLE
pconnect

### ISSUE THREAD

**Issue by wozzup** [SergeyTsalkov/meekrodb#29]
Mr.Tsalkov, how to use meekrodb in persistent pconnect way?

**Comment by mikegioia** [comment]
@wozzup Check out the documentation for the mysqli constructor: http://php.net/manual/en/mysqli.construct.php

> **host**
> ...
> Prepending host by p: opens a persistent connection. mysqli_change_user() is automatically called on connections opened from the connection pool.

I haven't tested this, and MeekroDB uses `real_connect()` but I think that function could behave the same way as the constructor with respect to hostname.

**Comment by wozzup** [comment]
awesome! thank you Mr.Tsalkov have nice day!
