### ISSUE TITLE
function request : row availability check 

### ISSUE THREAD

**Issue by rjcrystal** [SergeyTsalkov/meekrodb#30]
a simple function to check if the row is available with input data.

**Comment by spidfire** [comment]
How do you mean? 
Something like:
```
$row = DB::query("SELECT * FROM users");

if(somefunction_to_check_if_the_row_exists($row,0)){
    // do your thing
}
```

**Comment by rjcrystal** [comment]
i mean like checkrowdata("table","column-name","data") which will return true or false

**Comment by SergeyTsalkov** [comment]
So you're trying to check if the users table has any rows? Why not
something like:

$count = DB::queryFirstField("SELECT COUNT(*) FROM users");
if ($count > 0) echo "Users has some rows!";

**Comment by rjcrystal** [comment]
yes i know an i am using that everywhere, i just thought if it could be converted into a function.
