### ISSUE TITLE
How i can change CHARACTER SET?

### ISSUE THREAD

**Issue by leadingcode** [SergeyTsalkov/meekrodb#31]
Hi, my DB in utf8_general_ci but i have a problen with character => ?????????? without normal name. 
How i can setup SET NAMES UTF8?

**Comment by spidfire** [comment]
`DB::$encoding = 'utf8';`

**Comment by leadingcode** [comment]
Sorry, I found a solution.
You need to call the method encoding:

DB::$encoding = 'utf8';
