### ISSUE TITLE
mysqli_kill()?

### ISSUE THREAD

**Issue by tozjerimiah** [SergeyTsalkov/meekrodb#32]
Hi,

Is there any way of getting a mysqli_thread_id so that mysqli_kill could be used?

Thanks

**Comment by SergeyTsalkov** [comment]
$mysqli = DB::get();
$thread_id = $mysqli->thread_id;
$mysqli->kill($thread_id);

**Comment by SergeyTsalkov** [comment]
```php
$mysqli = DB::get();
$thread_id = $mysqli->thread_id;
$mysqli->kill($thread_id);
```
