### ISSUE TITLE
WHERE OR clause not recognizing second condition

### ISSUE THREAD

**Issue by lt3be** [SergeyTsalkov/meekrodb#35]
When trying to do a simple WHERE ... OR clause, the results returned only includes the first conditional.  The second is ignored.

```
$messages = DB::query("SELECT * FROM messages WHERE to_id=%i OR from_id=%i", $userid);
```

This returns only messages where the to_id = $userid but does not include messages where from_id = $userid.

The query works as expected in phpMyAdmin (returning all messages where to_id or from_id = $userid).

**Comment by lt3be** [comment]
Disregard.

I hadn't realized that anything more than a basic, one-conditional WHERE requires a WhereClause('or').  I though that was an optional helper function.

**Comment by SergeyTsalkov** [comment]
WhereClause is optional. Your example above should be changed to:
```
$messages = DB::query("SELECT * FROM messages WHERE to_id=%i OR from_id=%i", $userid, $userid);
```

The variables in the SQL query are filled in one at a time.
