### ISSUE TITLE
how do you perform a search?

### ISSUE THREAD

**Issue by xensor** [SergeyTsalkov/meekrodb#36]
how would i go about doing a search using this?

SELECT \* FROM bbcodes WHERE name LIKE '%$query%' (old style) 

"SELECT \* FROM bbcodes WHERE name LIKE %ss",$query ( this is what i am trying to do.) 

%ss search string (string surrounded with % for use with LIKE) 

but when  i try this it gives no results

**Comment by SergeyTsalkov** [comment]
This is the correct syntax: `DB::query("SELECT * FROM bbcodes WHERE name LIKE %ss", $query);`

I can't really debug your environment, but if you post a self-contained script highlighting a bug with %ss, I'd be happy to look and issue a fix.

**Comment by xensor** [comment]
I actually figured that out a few days after posting this. 

Thanks though for verifying that this was the actual proper way of doing it. :)

**Comment by abides** [comment]
what about "SELECT * FROM bbcodes WHERE name LIKE '%test'" or "SELECT * FROM bbcodes WHERE name LIKE 'test%'" i mean start with phrase and end with phrase?

**Comment by SergeyTsalkov** [comment]
```php
DB::query("SELECT * FROM bbcodes WHERE name LIKE %s", '%test');
```
