### ISSUE TITLE
Documentation seems to be incorrect when using composer

### ISSUE THREAD

**Issue by steowens** [SergeyTsalkov/meekrodb#38]
Added following to composer.json require object:
`
"require": {
        ....
        "sergeytsalkov/meekrodb": "*"
    }
`
updated composer and now vendor contains folder for sergeytsalkov
verified existance of file **/vendor/sergeytsalkov/meekrodb/db.class.php**

added following file to projet **"/inc/dbinit.php"**
`<?php
require_once 'db.class.php';
DB::$user = 'test';
DB::$password = 'changeit';
DB::$dbName = 'test';
DB::$host = '127.0.0.1'; //defaults to localhost if omitted
DB::$port = '3306'; // defaults to 3306 if omitted
DB::$encoding = 'utf8'; // defaults to latin1 if omitted
?>
`

added following require statement to my **/index.php**

`
$root=pathinfo($_SERVER['SCRIPT_FILENAME']);
define ('BASE_FOLDER', basename($root['dirname']));
define ('SITE_ROOT',    realpath(dirname(__FILE__)));
define ('SITE_URL',    'http://'.$_SERVER['HTTP_HOST'].'/'.BASE_FOLDER);
require_once SITE_ROOT.'/inc/dbinit.php';
`
refresh url pointing to index.php and get following in error logs
`
[Sun May 15 10:47:34.980963 2016] [:error] [pid 11309] [client 127.0.0.1:54362] PHP Fatal error:  require_once(): Failed opening required 'db.class.php' (include_path='.:/usr/share/php') in /_...excluding path ,.._ /inc/dbinit.php on line 2
`
I would have thought that the composer autoload process would have loaded this file and the require_once would not be needed. but certainly it is wrong since it doesn't point to the correct path to the file  **/vendor/sergeytsalkov/meekrodb/db.class.php**

Here is the relevant composer.lock file contents:
`
        {
            "name": "sergeytsalkov/meekrodb",
            "version": "v2.3",
            "source": {
                "type": "git",
                "url": "https://github.com/SergeyTsalkov/meekrodb.git",
                "reference": "eb36858f1aff94ae1665900e681a1cfb78563ee1"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/SergeyTsalkov/meekrodb/zipball/eb36858f1aff94ae1665900e681a1cfb78563ee1",
                "reference": "eb36858f1aff94ae1665900e681a1cfb78563ee1",
                "shasum": ""
            },
            "require": {
                "php": ">=5.2.0"
            },
            "type": "library",
            "autoload": {
                "classmap": [
                    "db.class.php"
                ]
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "LGPL-3.0"
            ],
            "authors": [
                {
                    "name": "Sergey Tsalkov",
                    "email": "stsalkov@gmail.com"
                }
            ],
            "description": "The Simple PHP/MySQL Library",
            "homepage": "http://www.meekro.com",
            "keywords": [
                "database",
                "mysql",
                "mysqli",
                "pdo"
            ],
            "time": "2014-06-16 22:40:22"
        }
`

**Comment by steowens** [comment]
I think what is happening is that because the DB class has all static methods, the composer framework fails to autoload the class.  Composer loads classes in lazy fashion. I think to fix this issue you need to add a non static method to DB and have the user call that method rather than doing the require_once that you currently do in the documentation.

**Comment by SergeyTsalkov** [comment]
Just get rid of the require_once() and you'll be fine. You're not supposed to require the files yourself if you're using composer to autoload them.
