### ISSUE TITLE
Relations?

### ISSUE THREAD

**Issue by aolko** [SergeyTsalkov/meekrodb#39]
Is it possible to use relatioins and how to use them?

**Comment by spidfire** [comment]
There is no relational info available. So you need to write it yourself or
look into ORM.

**Comment by aolko** [comment]
well, it would be awesome to have a similar relations mechanics to notorm

**Comment by aolko** [comment]
still waiting

**Comment by SergeyTsalkov** [comment]
MeekroDB is not an ORM. The goal is to let you write insert/select/update/delete queries more easily, not to abstract them away as an ORM does. Relations are more of an ORM feature, one that exists at a different level of abstraction from this project.
