### ISSUE TITLE
License confusion... what license is MeekroDB actually available under..?

### ISSUE THREAD

**Issue by Chris-Turnbull** [SergeyTsalkov/meekrodb#40]
Hi there, I'm an open-source developer working on a BSD-licensed project. I'm just wondering what license MeekroDB uses?

- The websites says it's free for personal use but you need to pay for commercial use.
- The GitHub listing says it's full GPL.
- The comments in the source code say that the license is LGPL.

By the way, I'm not saying any of the above is wrong. It's your project, and your choice of license!

However for a BSD-licensed project:

- We're redistributing our project for free so can't include a paid library.
- We can't include a GPL library because of the viral clause when redistributing makes it incompatible with BSD.
- LGPL is fine to use!

...so obviously I'd need to be sure as to which one it uses!

**Comment by spidfire** [comment]
@SergeyTsalkov Any comment on this?

**Comment by SergeyTsalkov** [comment]
I'm sorry about the confusion, and the delay in fixing the problem! I just fixed the github repo to reflect the fact that it's LGPLv3. The license on the website is really optional -- some companies actually prefer to pay for the software they use to make sure small projects stay alive! =)
