### ISSUE TITLE
Noobie question

### ISSUE THREAD

**Issue by ftyteca** [SergeyTsalkov/meekrodb#42]
Hi there and thanks for your work
I stop developping almost 10 years ago and I'm trying to build php app again.
I met a problem with your class in order to use it in another class.
I want to do this kind of thing.

A class
```
class foo{
 public $db;
  public function __construct($dbObj){
    $this->db = $dbObj;
  }

  public function getList(){
    $results = $this->db->query("SELECT * FROM foo ");
    if ($this->db->count()<=0){return NULL;}
    else{return $results;}
  }
};
```

The "classic" way (in my memories)
```
$db = new DB($dbhost, $dbname, $dbuser, $dbpass);
$fooObj = new foo($db);
$list = $fooObj -> getList();
```

The MeekroDB Way
```
DB::$host           = _DB_HOST;
DB::$user           = _DB_USER;
DB::$password       = _DB_PASS;
DB::$dbName         = _DB_NAME;
$fooObj = new foo(DB::get());
$list = $fooObj -> getList();
```
When I do so I get an error on **Call to undefined method mysqli::count()**.

What is the good way to use MeekroDb in the foo class ?
Many thanks.

**Comment by spidfire** [comment]
DB::$host           = _DB_HOST;
    DB::$user           = _DB_USER;
    DB::$password       = _DB_PASS;
    DB::$dbName         = _DB_NAME;
    $result = DB::queryFirstField("SELECT count(*) FROM foo");

Or alternatively

    $records = DB::query("SELECT * FROM foo");
    $alternative_result = DB::count(); // gets it from the last query

Or alternatively2

    $records = DB::query("SELECT * FROM foo");
    $alternative_result = count($records);

`DB::` makes a connection magically you could alternatively use the 

    $mdb = new MeekroDB($host, $user, $pass, $dbName, $port, $encoding);
    $records = $mdb->query("SELECT * FROM foo");

**Comment by ftyteca** [comment]
In fact I would like to know how to pass the DB obj in my foo class in order to use it with some kind of 
$foo->db->count or $foo->db->query

**Comment by spidfire** [comment]
Its untested but something like this? 


	class Foo{
		private $foo;

		function __constructor($foo){
			$this->foo = $foo;
		}

		function getList(){
			$records = $this->foo->query("SELECT * FROM foo");
			$count_result = $this->foo->count();
		}
	}


	$db = new DB($dbhost, $dbname, $dbuser, $dbpass);
	$bar = new Foo($db);
	$bar->getList();

**Comment by ftyteca** [comment]
with your help here is our solution :)

```
use sergeytsalkov\meekrodb;
DB::$host           = _DB_HOST;
DB::$user           = _DB_USER;
DB::$password       = _DB_PASS;
DB::$dbName         = _DB_NAME;
DB::$encoding       = 'utf8';
DB::$error_handler  = 'myErrorHandler';
// then init the object (again ?) - I have to read to understand this part
$db = new DB(); // not MeekroDB

$bar = new Foo($db);
$bar->getList();
```
And that work

If I do what I was thinking at first 
`$db = new MeekroDB($host, $user, $pass, $dbName, $port, $encoding);`
I get a 'Class sergeytsalkov\meekrodb' not found.

By the way many thanks for your help :)
