### ISSUE TITLE
Namespace and whereClause in another class

### ISSUE THREAD

**Issue by ftyteca** [SergeyTsalkov/meekrodb#43]
Hi again
Sorry to be back but I've done many tests and I cannot find a solution to my noobie problem of namespace.
The goal : using the WhereClause in another class/namespace.

I wrote this test
foo.php
```
<?php
require __DIR__.'/config.inc.php';
require __DIR__.'/vendor/autoload.php';

use sergeytsalkov\meekrodb;
DB::$user           = _DB_USER;
DB::$host           = _DB_HOST;
DB::$password       = _DB_PASS;
DB::$dbName         = _DB_NAME;
DB::$encoding       = 'utf8';

$db = new DB();

include __DIR__.'/class_foo.php';
$foo = new foo\foo($db);
$result = $foo->getFoo();
?>
```
And this class class_foo.php
```
<?php
namespace foo;
class foo{
  public $db;
  public function __construct($dbObj){
    $this->db = $dbObj;
    echo "Class foo ok".PHP_EOL;
  }

  public function getFoo(){

    /* Uncaught Error: Class 'foo\WhereClause' not found
    $where = new WhereClause('and');
    $where->add('media_id=%s', 'Upxqhd_htzw');
     */
    // Uncaught Error: Class 'sergeytsalkov\meekrodb\WhereClause' not found
    $where = new \sergeytsalkov\meekrodb\WhereClause('and');
    $where->add('media_id=%s', 'Upxqhd_htzw');

    $results = $this->db->query("SELECT * FROM medias WHERE %l", $where);
    /* I know I could do this but I would want to know how to use whereClause in another namespace class
      $results = $this->db->query("SELECT * FROM medias WHERE media_id=%s", 'Upxqhd_htzw');
     */
    if ($this->db->count()<=0){return NULL;}
    else{return $results;}
  }
};
?>
```

Whatever I try to use WhereClause in my foo class, it fails.
If you have a solution or explanation it will be greatly appreciated.
Regards
PS : the example is much less complicated than in my true class but bases are the same.

**Comment by spidfire** [comment]
I think you can probably add either under the namespace definition:
   
```
namespace foo;    
use \WhereClause;
```

or just use `new \WhereClause('and');`

**Comment by ftyteca** [comment]
The WhereClause class is in the same file/namespace that the DB class so even if I don't understand why, It works.
thanks for your help again :)

**Comment by spidfire** [comment]
the foo.php is outside of a namespace so looks for classes in the root (e.g. in \ )
inside class_foo.php you specified the namespace so it will look in the namespace (e.g. in \foo\) and in that case it will try to access `\foo\WhereClause`.

This will also happen if you try to throw an exception like `throw new \Exception()` inside the class_foo.php file

**Comment by ftyteca** [comment]
thanks again :)
