### ISSUE TITLE
Get the last query

### ISSUE THREAD

**Issue by ftyteca** [SergeyTsalkov/meekrodb#44]
Hi again

I love asking noob questions but : **is there a proper way to get the last query ?** 
By example

```
$attendedResults = X;
$results = DB::query("SELECT ... FROM ... WHERE ... AND ... AND ... AND ... AND ... ORDER BY ...", $var1, $var2, $var3, $var4, $var5, $var6,  );
if ($results != $attendedResults){
  echo "Something went wrong with this query : ".DB::lastQuery().PHP_EOL;
}
```
Regards

**Comment by spidfire** [comment]
As far as I know there are only commands to get some data from the last queries
http://meekro.com/docs.php#anchor_insertid

And also if you got the last query in an error you could potentially run into security issues.

But what you are probably are looking for is a way to see the filled query, this can be done by using `DB::debugMode()`
http://meekro.com/docs.php#anchor_debugmode

But please be sure to remove them after you're done ;)

**Comment by ftyteca** [comment]
In fact I have a script which is playing lot of queries. And for some of them the result is NULL. I would like to display only the queries in this case.

**Comment by spidfire** [comment]
In that case just put the query you want to debug between the debug mode commands

    DB::debugMode()
    // Your query
    DB::debugMode(false);

**Comment by ftyteca** [comment]
Hi Spidfire and thanks for your help
I will try this :)
