### ISSUE TITLE
DB::insertUpdate() with an array of associative arrays?

### ISSUE THREAD

**Issue by linguica** [SergeyTsalkov/meekrodb#45]
Hi, I recently switched my MySQL setup to use its own dedicated server accessed over the network, and I appreciate how MeekroDB lets me build up a big array of queries to run all at once, to minimize slowdowns from latency (it may only be a 500 microsecond round trip between the web server and the MySQL server, but it adds up...) One thing I have noticed, however, is that DB::insert() and DB::insertIgnore() will both take an array of arrays, but DB::insertUpdate() will not, making it relatively slow. I'm just wondering if there is a method for doing this with Meekro, or if it's a limitation within MySQL, or something else.

**Comment by spidfire** [comment]
I see in the MySQL documentation that its possible with the VALUES() function:
https://dev.mysql.com/doc/refman/5.7/en/insert-on-duplicate.html

    INSERT INTO table (a,b,c) VALUES (1,2,3),(4,5,6)
     ON DUPLICATE KEY UPDATE c=VALUES(a)+VALUES(b);
 
I would suggest you to propose a way to implement it and create a pull request if you have the time 😄

**Comment by 32Blahs** [comment]
It does work, I just tried it. Assumes you have a primary key / unique index for "ID"

```
$arrayStuff = array();
for($i = 0; i < 10; i++)
    $arrayStuff[] = array("ID" => $i, "Stuff" = "blah ".$i);

meekro::insertUpdate("mytable", $arrayStuff, array("Stuff" => "updated!!"));
```
