### ISSUE TITLE
Use "IS NULL"

### ISSUE THREAD

**Issue by tcolonel** [SergeyTsalkov/meekrodb#46]
Hello Sergey.

How I can use "IS NULL" with params?

For example, I have this request:
```
$arResult = DB::query("SELECT * FROM tbl WHERE ID=%s AND (sExpireDate >= %s OR sExpireDate IS NULL)", $_USER['ID'], date('Y-m-d H:i:s'));
```
In this case I ghave an nGinx error: 502 Bad Gateway.

If I use this code:
```
$arResult = DB::query("SELECT * FROM tbl WHERE ID=%s AND sExpireDate >= %s)", $_USER['ID'], date('Y-m-d H:i:s'));
```
I have no errors.

Thanks.

**Comment by SergeyTsalkov** [comment]
There's nothing wrong with your queries here, but debugging your environment isn't something I can do.
