### ISSUE TITLE
$db values changed in between statements

### ISSUE THREAD

**Issue by bwsolutions** [SergeyTsalkov/meekrodb#48]
Somehow the $db object is having values changed in the section of the queryHelper() below.
With a call to $db->query().  This works fine, the SQL has a syntax error and the values get set properly in the $db object.  "errno" is set to 1052 and "error" has a text string.
Then in the debugger, I step one line, which is "If ($this->success_handler)..."
And suddenly the error has be "reset"???  "errno" =0 and "error" = ''.
How is this possible? There is not any time to check $db->error to call the error_handler???

`
$result = $db->query($sql, $is_buffered ? MYSQLI_STORE_RESULT : MYSQLI_USE_RESULT);
    if ($this->success_handler) $runtime = microtime(true) - $starttime;
 else $runtime = 0;

    // ----- BEGIN ERROR HANDLING
    if (!$sql || $db->error) {`

**Comment by SergeyTsalkov** [comment]
Could you submit a small and self-contained script that triggers the bug? I'm not totally clear what you're saying, and no one else has complained about anything similar.
