### ISSUE TITLE
Multiple databases

### ISSUE THREAD

**Issue by Cinamonas** [SergeyTsalkov/meekrodb#5]
The library's great. The only thing I'm missing is setting it up for multiple databases, let's say like this:

``` php
<?php
$db1 = new MeekroDB(array(
    'dbName' => 'one',
    // ...
));
$db2 = new MeekroDB(array(
    'dbName' => 'two',
    // ...
));
$res1 = $db1->query('SELECT ...');
$res2 = $db2->query('SELECT ...');
```

Are you planning to implement this?

**Comment by muhammadarsalansiddiqui** [comment]
I also want to use multiple database, i can change database name only. What if there is separate username or password for second database and if it is externally hosted server i have to add ip for that.

kindly add support for multiple database with parameter.

Thanks

**Comment by SergeyTsalkov** [comment]
We support creating object instances of MeekroDB so you can access multiple databases. See: https://meekro.com/docs/static-vs-object.html

**Comment by muhammadarsalansiddiqui** [comment]
but you do not have much examples in oop. and you recommend in docs to use static

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
