### ISSUE TITLE
Re-use connection

### ISSUE THREAD

**Issue by ponasromas** [SergeyTsalkov/meekrodb#51]
Hello,

I would like to re-use same connection for another library. Trying like this:

```
...
$reconnect = new MeekroDB();
$auth = new \Delight\Auth\Auth($reconnect);
...
```
And of course this is results in error. Any suggestions how to re-use meekrodb connection if third party library requires:

> The database connection must be an instance of either `PdoDatabase`, `PdoDsn` or `PDO`?

**Comment by Nrde** [comment]
Meekro is not compatible with PDO. So you can't. Just make a PDO connection for your auth library.
