### ISSUE TITLE
DB::query optional Placeholder Variables

### ISSUE THREAD

**Issue by soukupl** [SergeyTsalkov/meekrodb#53]
I'm missing one small thing that can make my life easier. It is "optional placeholder".

Example:
`
DB::query("SELECT * FROM tbl WHERE name=%s[ AND age > %I]", "test", 15);
`
This will result in:
`
SELECT * FROM tbl WHERE name='test' AND age > 15
`

But this example:
`
DB::query("SELECT * FROM tbl WHERE name=%s[ AND age > %I]", "test", null);
`
will result in:
`
SELECT * FROM tbl WHERE name='test'
`

So it will allow having one query and "one" line of code to make SQL with optional WHERE, ORDER BY, ... rules.
Not sure how big change will this be in your code. I was used to using this in EzSQL lib that I switched from (still like meekro better). I don't need this, but it can be a time saver in some cases.

btw: I'm aware of the existence of `new WhereClause('and');`, but this optional placeholder can result in more compact code (not always)

**Comment by SergeyTsalkov** [comment]
I've thought about this off-and-on for a while, and I would prefer not to do that. It really feels like an ugly solution to the problem, and a query builder (such as the WhereClause tool) is a better approach it.
