### ISSUE TITLE
Why there is no mysqli_close()!

### ISSUE THREAD

**Issue by beshoo** [SergeyTsalkov/meekrodb#55]
I can find KILL function 

   ```
 public function disconnect()
    {
        $mysqli = $this->internal_mysql;
        if ($mysqli instanceof MySQLi)
        {
            if ($thread_id = $mysqli->thread_id) $mysqli->kill($thread_id);
            $mysqli->close();
        }
        $this->internal_mysql = null;
    }
```

But why dont you use mysqli_close ! 
and what is this function : $mysqli->close(); i can not find it !

**Comment by tomo54321** [comment]
$mysqli->close() and mysqli_close($mysqli) would do the exact same. $mysqli->close() is object based whereas mysqli_close($mysqli) would be procedural style.
