### ISSUE TITLE
strtolower affected by locale

### ISSUE THREAD

**Issue by magma1447** [SergeyTsalkov/meekrodb#57]
I have been using MeekroDB for years and finally managed to understand a bug I have been seeing at times.

In MeekroDBs code there is use of the PHP  function strtolower(). If doing an insertUpdate, it will get to this compare:
`if (isset($options['update']) && is_array($options['update']) && $options['update'] && strtolower($which) == 'insert') {`

If the locale is set to Turkish, the above if statement will fail. More precisely the last part of it.
strtolower('INSERT') does not equal 'insert' when the locale is Turkish.

Instead mb_strtolower() could be used, which is documented to **not** be affected by locale. This is what I have updated my local copy to use.
mb_convert_case() could most likely also be used, but I haven't tried it.

The fix is quite easy. Search and replace all strtolower into mb_strtolower.

**Comment by magma1447** [comment]
Reproduction case:
```
<?php
setlocale(LC_ALL, 'tr_TR.UTF-8');
var_dump( strtolower('INSERT') );
var_dump( strtolower('INSERT') == 'insert' );
```

I can reproduce it with PHP 7.0.27.

With PHP 7.2.24 and 7.4.1 the lib works as it should. Not sure if it's a PHP bug or it because of an installed module. Regardless strtolower actually is documented to be affected by locale.

**Comment by SergeyTsalkov** [comment]
Thanks for the bug report! Can you try it with the fix I just pushed?

**Comment by magma1447** [comment]
I didn't test your code per say since I am using it with a few (minor) local patches. I should look into breaking them up into patches and send you two pull requests, so you can review it and if you are interested, you can merge them. Otherwise, I just keep them locally.

Using strtoupper() seems to work, at least in the specific case I found (second var_dump below). But if the input is ever 'insert', it won't work (third var_dump).

I have tried to review your code, and I actually haven't been able to find a reason for changing case in the compare. It seems that $which is always upper case in the case of insert. I will take a leap of faith and actually remove my mb_strtolower() and compare with INSERT instead on my Live-servers.

If you know why there was a strtolower() at all, please enlighten me. Maybe I missed something smart.

The below has been run on my  PHP 7.0.27-0+deb9u1 which is where I found the issue.
```
$ php -a
Interactive mode enabled

php > setlocale(LC_ALL, 'tr_TR.UTF-8');
php > var_dump( strtolower('INSERT') == 'insert' );
bool(false)
php > var_dump( strtoupper('INSERT') == 'INSERT' );
bool(true)
php > var_dump( strtoupper('insert') == 'INSERT' );
bool(false)
```
I can not answer for if there are other cases with similar issues though. Maybe other locales causes issues with strtoupper instead? It seems a bit hard to write a proper test for it.

**Comment by SergeyTsalkov** [comment]
I made more cleanups that dropped the use of strtolower() and strtoupper() in that function, and added a check so it'll return an error if the value is unexpected. I think this should definitely work for you. Please re-open this issue if it doesn't.

Also, feel free to open pull requests for your other ideas. Or just open issues with suggestions, if you prefer!
