### ISSUE TITLE
How to get last executed SQL

### ISSUE THREAD

**Issue by tohizma** [SergeyTsalkov/meekrodb#60]
Is there any way to debug complex query statements with seeing what is final SQL string resulted from meekrodb parsing and processing?

Needs some kind of DB::getLastQueryString()

Thank you

**Comment by SergeyTsalkov** [comment]
So you want to see the last successful query? You can enable debug mode, and just look at the queries being spit out and see which one's last. Or look up how to set your own success handler, and attach a function that will overwrite a variable. Maybe something like this:

```php
DB::$success_handler = function($params) {
  global $last_query_string;
  $last_query_string = $params['query'];
}
```

Now the global variable `$last_query_string` will store the final query. You could also log each query to a file if you wanted.

**Comment by ryangriggs** [comment]
Why not just use DB::$last_query?  That works in older versions; has it been removed from the most recent version?

**Comment by SergeyTsalkov** [comment]
@ryangriggs Apparently so, I'm not sure when that happened but it wasn't recently! Anyway, it's back as `DB::lastQuery()` in today's release and with unit tests added so it doesn't vanish again.

**Comment by ryangriggs** [comment]
Awesome, thanks!

-------------------------
Ryan Griggs
Hilltop Computing
www.hilltop.net
859-328-3223
Toll Free: 1 (888) 5-HILLTOP (888-544-5586)
