### ISSUE TITLE
Get Last Insert ID and Affected Rows

### ISSUE THREAD

**Issue by ameshkin** [SergeyTsalkov/meekrodb#62]
Forgive me if there is something I have missed but I am trying to figure out how to get data back from the functions.

For instance, let's say I have this query.  No matter what, it returns a 1.   If it deletes a row, it returns 1.  But if there is no row to delete, it still returns 1.

This makes it hard for me to figure out how to handle output to the user

`    return DB::query("DELETE  FROM $table WHERE url = %s", $site);`

**Comment by SergeyTsalkov** [comment]
Look up `DB::insertId()` and `DB::affectedRows()` in the documentation.
