### ISSUE TITLE
White spaces are removed with "%s" placeholder

### ISSUE THREAD

**Issue by mattialazzaroni** [SergeyTsalkov/meekrodb#63]
Hi, I have this line:
`DB::query("INSERT INTO order (id, state) VALUES (%i, %s)", $id, $state);`
where for example $state = "order paid and delivered". The problem is that when I execute the query and then go to look in the database, I see state column with value "orderpaidanddelivered" (without spaces). Where am I doing wrong?

**Comment by SergeyTsalkov** [comment]
The line you pasted looks correct, so I think there's a bug somewhere else in your code. I wonder if the value of $state is what you think it is. Does this still happen if you set it explicitly? 

```php
$state = "order paid and delivered";
DB::query("INSERT INTO order (id, state) VALUES (%i, %s)", $id, $state);
```

**Comment by mattialazzaroni** [comment]
Ye, my bad, thank you.
