### ISSUE TITLE
sync_config() problem with PHP7

### ISSUE THREAD

**Issue by sir-oliver** [SergeyTsalkov/meekrodb#64]
I'm having a hard time getting `DB::$success_handler `and `DB::$error_handler` to work when calling the method statically.
I have used them before in PHP 5.5 with no problems, but under PHP 7.4 it just won't work.
I think i located the problem in the sync_config() method, which should suck in the setting from the static class, but other than in PHP5 the function `get_class_vars()` behaves different in PHP7 and just returns the default values of the variables instead of the user-set values.
```
public function sync_config() {
  $db_class_vars = get_class_vars('DB')
  ...
}
```
here is a simple test:
```
<?php
require_once('meekrodb/db.class.php');
DB::$encoding	= 'utf8';
DB::$success_handler = 'mysuccess';
DB::$error_handler = 'myerror';
print_r(get_class_vars('DB'));
?>
```
in the output the three variables are shown with their default value. 
```
Array
--
  | (
  | [dbName] =>
  | [user] =>
  | [password] =>
  | [host] => localhost
  | [port] => 3306
  | [socket] =>
  | [encoding] => latin1
  | [param_char] => %
  | [named_param_seperator] => _
  | [success_handler] =>
  | [error_handler] => 1
  | [throw_exception_on_error] =>
  | [nonsql_error_handler] =>
  | [throw_exception_on_nonsql_error] =>
  | [nested_transactions] =>
  | [usenull] => 1
  | ...
  | )
```

**Comment by sir-oliver** [comment]
I patched to sync_config() to work with PHP7+

```
public function sync_config() {
  foreach (DB::$variables_to_sync as $variable) {
    if ($this->$variable !== DB::$$variable) {
      $this->$variable = DB::$$variable;
    }
  }
}
```

**Comment by wadih** [comment]
@sir-oliver Thank You, I was having the same issue. My version of PHP is 7.4.3, custom error handling just wouldn't work. Though I remember it working before as I used meekroDB before as well.

**Comment by SergeyTsalkov** [comment]
Sorry about the delay-- I'll get a published fix out within a few days!

**Comment by wadih** [comment]
Thanks @SergeyTsalkov !

**Comment by sir-oliver** [comment]
Thanks @SergeyTsalkov !

**Comment by SergeyTsalkov** [comment]
I've been unable to reproduce this issue so far. MeekroDB's entire test suite passes for me on PHP 7.4.7. I came up with this simple snippet to explore the get_class_vars() issue you guys are talking about:

```php
<?php
class MyClass {
  public static $v = 'a';
}

echo phpversion() . "\n";
print_r(get_class_vars('MyClass'));
MyClass::$v = 'b';
print_r(get_class_vars('MyClass'));
```

The output I get is this:
```php
7.4.7
Array
(
    [v] => a
)
Array
(
    [v] => b
)
```

Which means that get_class_vars() is showing the current value, not the default value. I also tried using https://3v4l.org to run this code snippet on 7.4.3, and I'm still getting that same behavior.

Could you guys run my test snippet and see what you get? Also, could you give me the exact details to reproduce? I tried reproducing on a clean DigitalOcean droplet running Ubuntu 20.04LTS and I'm still getting the same (working fine) behavior.

**Comment by wadih** [comment]
Hi @SergeyTsalkov 

Interesting, strangely it also works through cli for me too as I try this morning. But it doesn't work when run through apache2 mod_php:

This exact same code works in cli, but not through apache2:

```
include 'db.class.php';

DB::$user = 'xx';
DB::$password = 'xx';
DB::$dbName = 'xx';

DB::$error_handler = 'my_error_handler2'; // runs on mysql query errors
DB::$nonsql_error_handler = 'my_error_handler2'; // runs on library errors (bad syntax, etc)

function my_error_handler2($params) {
    echo "Error2: " . $params['error'] . "<br>\n";
    echo "Query2: " . $params['query'] . "<br>\n";
    die; // don't want to keep going if a query broke
}

//DB::query('selet 1');
DB::query("SELCT * FROM accounts"); // misspelled SELECT
```

Output in cli:

```
php run.php 
Error2: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'SELCT * FROM accounts' at line 1<br>
Query2: SELCT * FROM accounts<br>
```

Output through apache2 mod_php - e.g. http://localhost/run.php, same exact php file: 

```
QUERY: SELCT * FROM accounts
ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'SELCT * FROM accounts' at line 1
```

We can see it uses the default error_handler instead of my_error_handler2 when run through apache2.

Versions (latest stable): 
Apache/2.4.41 (Ubuntu)
PHP 7.4.3 (cli)

When applying @sir-oliver's patch, it then works in apache2 too for me.

**Comment by wadih** [comment]
Much more interesting... this is very strange. 

I used your code for testing:

```
class MyClass {
    public static $v = 'a';
}

echo '<pre>';
echo phpversion() . "\n";
print_r(get_class_vars('MyClass'));
MyClass::$v = 'b';
print_r(get_class_vars('MyClass'));
```

First time it runs, it prints: 

```
7.4.3
Array
(
    [v] => a
)
Array
(
    [v] => b
)
```

Refresh the page, and now it prints (!!): 

```
7.4.3
Array
(
    [v] => a
)
Array
(
    [v] => a
)
```

Now modify the php page (do a dummy change, e.g. add another `echo <pre>` at the top, so my code becomes this: 

```
class MyClass {
    public static $v = 'a';
}

echo '<pre>';
echo '<pre>';
echo phpversion() . "\n";
print_r(get_class_vars('MyClass'));
MyClass::$v = 'b';
print_r(get_class_vars('MyClass'));
```

It now prints:

```
7.4.3
Array
(
    [v] => a
)
Array
(
    [v] => b
)
```

Refresh again, and it goes back to (!)

```
7.4.3
Array
(
    [v] => a
)
Array
(
    [v] => a
)
```

The same call to get_class_vars() prints different values depending if it's the first time I run it, or if it's subsequent times.

@sir-oliver  @SergeyTsalkov Are you able to reproduce?

**Comment by SergeyTsalkov** [comment]
I can reproduce the opcache issue on a clean Ubuntu 20.04LTS install. I'm checking if there are known bugs..

**Comment by wadih** [comment]
@SergeyTsalkov Ok. I looked at past bugs regarding `get_class_vars()`, but didn't find a bug report where opcache triggers this behavior.

I filed PHP bug 79822 https://bugs.php.net/bug.php?id=79822 . 

Not sure if get_class_vars() should be relied upon, since opcache is now enabled by default? I don't have much experience with that function, but seeing how it behaved in this case, it's a bit strange.

**Comment by SergeyTsalkov** [comment]
Ok, you win, I guess I have to break PHP 5.2 compatibility by making this change! =(

**Comment by wadih** [comment]
Hi @SergeyTsalkov !

I'm not sure what the best course of action would be at that stage. But thinking about it! 

Perhaps there's a way to do it without breaking backwards compatibility.
