### ISSUE TITLE
Support SQLite

### ISSUE THREAD

**Issue by n1trux** [SergeyTsalkov/meekrodb#66]
Hi, I really like using meekroDB for MySQL databases.

However I'd like to use it for SQLite DBs as well. Would it be possible to add support for that?

**Comment by SergeyTsalkov** [comment]
I've thought about switching the next major release to PDO as a backend (we currently use mysqli). That's what would have to happen to allow sqlite and other databases. That's the plan for the next version, but I'm not sure yet when that will be.

**Comment by SergeyTsalkov** [comment]
I did a moderate-sized cleanup release today, but haven't gotten around to this yet. I'm still thinking about multiple database support. I expect to do it later this year.

**Comment by ponasromas** [comment]
Sergey, personally I will eagerly wait for renewal :) your lib is amazing and helped me a lot!

**Comment by betim** [comment]
Sergey if you switch to PDO then I think it should be a different project name since PDO also has a performance hit

**Comment by danielscsc** [comment]
I needed to use SQLite for something today, and decided to check-in here and see if support was ever added (I still always use Meekro for MySQL).  Seems not yet 😢   However, I did notice that this package seemed to be incorrectly tagged as `#pdo` on packagist.  I assume that comes from the `pdo` keyword [in composer.json](https://github.com/SergeyTsalkov/meekrodb/blob/08b683a274365983aaf033cf9c589dcbe5190028/composer.json#L12).  Is that a mistake? 

Thanks again for this great package!

**Comment by SergeyTsalkov** [comment]
Are you guys able to test the pdo branch? It's quite stable and passes my whole test suite (on MySQL and SQLite). It can connect to any PDO DSN like this:

```php
DB::$dsn = 'sqlite:';
```

**Comment by danhaber** [comment]
Wow this is exciting!! Will try it tomorrow!  Thank you!

**Comment by danhaber** [comment]
I didn't specify a dsn (I assume it defaults to mysql?).

I have a pre-run hook:
```PHP
  DB::addHook('pre_run', function ($q) {
    $trace = debug_backtrace();
    $fromFirstRow = array_filter($trace, function ($stack) {
      return isset($stack['function']) && $stack['function'] == 'queryFirstRow';
    });

    $query = $q['query'];

    if ($fromFirstRow && !str_contains($query, ' LIMIT 1')) {
      $query .= ' LIMIT 1';
    }

    return $query;
  });

```

I get this error:
`pre_run hook must return a [query, params] array`

**Comment by SergeyTsalkov** [comment]
Yeah, pre_parse and pre_run have been merged into a single hook. This was necessary because of how things function now. Old MeekroDB would escape() all of your params and build up a single query to execute. The new PDO-as-backend approach "compiles into" a PDO query with ?'s for all params, and then lets PDO handle the heavy lifting of escaping.

The point is, you'll need to change your return line in your example to look like this:
```php
return [$query, $q['params']];
```

I'll see if I can add some backwards compatibility here since you already tripped over this.

**Comment by danhaber** [comment]
I don’t think you need to work too hard on backwards compatibility for
this. Your docs are very clear - if you update them with the new release it
should be more than enough.

**Comment by SergeyTsalkov** [comment]
It was no trouble, only took a couple lines of change to add the backwards compatibility in: https://github.com/SergeyTsalkov/meekrodb/commit/158e53b9400147d1083ff85761b7ff34ec6fb092

I'm pretty eager to hear about whether it works for you with SQLite, though! =)

**Comment by danhaber** [comment]
> It was no trouble, only took a couple lines of change to add the backwards compatibility in: [158e53b](https://github.com/SergeyTsalkov/meekrodb/commit/158e53b9400147d1083ff85761b7ff34ec6fb092)

Thanks!

> I'm pretty eager to hear about whether it works for you with SQLite, though! =)

Did some quick testing - and it worked!  Will need to give it some more attention later this week.

This is really exciting!  Thank you so much for the time and work you put into this!

**Comment by SergeyTsalkov** [comment]
The new v3 release has published this feature.
