### ISSUE TITLE
Updating JSON type

### ISSUE THREAD

**Issue by ponasromas** [SergeyTsalkov/meekrodb#67]
Hello,

recently I had a task to update JSON data type field in MySQL 8. 

When there is no data, simple query is fine:

`DB::query("UPDATE websites SET settings = %? WHERE status = %i", json_encode($website_settings), 1);`

Now with updating JSON values inside of that 'settings' column is a bit tricky:

`DB::query("UPDATE websites SET settings = JSON_SET(settings, \"$.ip_access\", '127.0.0.1,22.22.33.55,11.44.55.66') WHERE status = %i",1);`

The main concern is: how properly escape this? This variant is no go:

`DB::query("UPDATE websites SET settings = JSON_SET(settings, \"$.ip_access\", %?) WHERE status = %i", '127.0.0.1,22.22.33.55,11.44.55.66', 1);`

**Comment by SergeyTsalkov** [comment]
Why is that variant a no go? It's exactly right. Here's my test script to prove it:
```php
DB::query("DROP TABLE IF EXISTS websites");
DB::query("CREATE TABLE `websites` (
  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  `settings` varchar(255) NOT NULL,
  `status` int NOT NULL
  ) ENGINE = InnoDB");

DB::insert('websites', [
  'settings' => json_encode(['name' => 'Meekro', 'ip_access' => '192.168.1.1']),
  'status' => 1,
]);

DB::query("UPDATE websites SET settings = JSON_SET(settings, \"$.ip_access\", %?) WHERE status = %i", '127.0.0.1,22.22.33.55,11.44.55.66', 1);

$r = DB::query("SELECT * FROM websites");
var_dump($r);
```

and the results:
```
array(1) {
  [0]=>
  array(3) {
    ["id"]=>
    string(1) "1"
    ["settings"]=>
    string(68) "{"name": "Meekro", "ip_access": "127.0.0.1,22.22.33.55,11.44.55.66"}"
    ["status"]=>
    string(1) "1"
  }
}
```
