### ISSUE TITLE
Uncaught MeekroDBException

### ISSUE THREAD

**Issue by ponasromas** [SergeyTsalkov/meekrodb#71]
Updated to 2.4 version and bumped into problems... Hope it can be easily fixed.

```
PHP Fatal error:  Uncaught MeekroDBException: Incorrect integer value: '' for column `site`.`websites`.`quota_current` at row 1 in /var/www/dd.net/inc/vendor/sergeytsalkov/meekrodb/db.class.php:805
Stack trace:
#0 /var/www/dd.net/inc/vendor/sergeytsalkov/meekrodb/db.class.php(771): MeekroDB->queryHelper()
#1 /var/www/dd.net/inc/vendor/sergeytsalkov/meekrodb/db.class.php(398): MeekroDB->query()
#2 /var/www/dd.net/inc/vendor/sergeytsalkov/meekrodb/db.class.php(61): MeekroDB->update()
#3 /var/www/dd.net/api/collectors/wp_info.php(34): DB::__callStatic()
#4 {main}
```

Is it related to removed "MeekroDB->queryHelper()" method?

**Comment by SergeyTsalkov** [comment]
It is not related to that-- it looks like DB::update() is being used to produce a bad query? I would need a lot more details to investigate whether this is a bug. Could you give me a full example of the DB::update() statement that you think is doing the wrong thing?
