### ISSUE TITLE
DB::columnlist example in documentation not working (MariaDB issue?)

### ISSUE THREAD

**Issue by wfvdijk** [SergeyTsalkov/meekrodb#73]
The example for columnlist (https://meekro.com/docs/misc-methods.html ) is giving me an error "illegal string offset" for every columndetail. However, I am using MariaDB 10.4.14 is this causing the problem? Could you update the documentation about MariaDB compatibility?

**Comment by SergeyTsalkov** [comment]
This project has no compatibility problems with MariaDB. Could you check what the underlying SHOW COLUMNS outputs, like this:

```php
$result = DB::query("SHOW COLUMNS FROM %b", $table_name);
var_dump($result);
```

.. and then show me what the output was?

**Comment by wfvdijk** [comment]
array(5) { [0]=> array(6) { ["Field"]=> string(2) "id" ["Type"]=> string(19) "tinyint(3) unsigned" ["Null"]=> string(2) "NO" ["Key"]=> string(3) "PRI" ["Default"]=> NULL ["Extra"]=> string(14) "auto_increment" } [1]=> array(6) { ["Field"]=> string(12) "omschrijving" ["Type"]=> string(11) "varchar(32)" ["Null"]=> string(2) "NO" ["Key"]=> string(3) "UNI" ["Default"]=> NULL ["Extra"]=> string(0) "" } [2]=> array(6) { ["Field"]=> string(9) "isDefault" ["Type"]=> string(6) "bit(1)" ["Null"]=> string(2) "NO" ["Key"]=> string(0) "" ["Default"]=> string(4) "b'0'" ["Extra"]=> string(0) "" } [3]=> array(6) { ["Field"]=> string(8) "isActief" ["Type"]=> string(6) "bit(1)" ["Null"]=> string(2) "NO" ["Key"]=> string(0) "" ["Default"]=> string(4) "b'1'" ["Extra"]=> string(0) "" } [4]=> array(6) { ["Field"]=> string(11) "isAdminOnly" ["Type"]=> string(6) "bit(1)" ["Null"]=> string(2) "NO" ["Key"]=> string(0) "" ["Default"]=> string(4) "b'0'" ["Extra"]=> string(0) "" } } Column: 0

**Comment by wfvdijk** [comment]
<file>
<?php
require_once './class/external/db.class.php';
require_once './include/db.php';

$table_name = 'domain_soortorganisatie';
$columns = DB::columnList($table_name);
foreach ($columns as $name => $details) {
  echo "Column: $name\n";
  echo "Type: " . $details['type'] . "\n";
  echo "Null? " . $details['null'] . "\n";
  echo "Key: " . $details['key'] . "\n";
  echo "Default: " . $details['default'] . "\n";
  echo "Extra: " . $details['extra'] . "\n";
}
?>
</file>
<output>
Column: 0
Warning: Illegal string offset 'type' in D:\xampp\htdocs\deeleenrit\issue.php on line 9
Type: i
Warning: Illegal string offset 'null' in D:\xampp\htdocs\deeleenrit\issue.php on line 10
Null? i
Warning: Illegal string offset 'key' in D:\xampp\htdocs\deeleenrit\issue.php on line 11
Key: i
Warning: Illegal string offset 'default' in D:\xampp\htdocs\deeleenrit\issue.php on line 12
Default: i
Warning: Illegal string offset 'extra' in D:\xampp\htdocs\deeleenrit\issue.php on line 13
Extra: i Column: 1
Warning: Illegal string offset 'type' in D:\xampp\htdocs\deeleenrit\issue.php on line 9
Type: o
Warning: Illegal string offset 'null' in D:\xampp\htdocs\deeleenrit\issue.php on line 10
Null? o
Warning: Illegal string offset 'key' in D:\xampp\htdocs\deeleenrit\issue.php on line 11
Key: o
Warning: Illegal string offset 'default' in D:\xampp\htdocs\deeleenrit\issue.php on line 12
Default: o
Warning: Illegal string offset 'extra' in D:\xampp\htdocs\deeleenrit\issue.php on line 13
Extra: o Column: 2
Warning: Illegal string offset 'type' in D:\xampp\htdocs\deeleenrit\issue.php on line 9
Type: i
Warning: Illegal string offset 'null' in D:\xampp\htdocs\deeleenrit\issue.php on line 10
Null? i
Warning: Illegal string offset 'key' in D:\xampp\htdocs\deeleenrit\issue.php on line 11
Key: i
Warning: Illegal string offset 'default' in D:\xampp\htdocs\deeleenrit\issue.php on line 12
Default: i
Warning: Illegal string offset 'extra' in D:\xampp\htdocs\deeleenrit\issue.php on line 13
Extra: i Column: 3
Warning: Illegal string offset 'type' in D:\xampp\htdocs\deeleenrit\issue.php on line 9
Type: i
Warning: Illegal string offset 'null' in D:\xampp\htdocs\deeleenrit\issue.php on line 10
Null? i
Warning: Illegal string offset 'key' in D:\xampp\htdocs\deeleenrit\issue.php on line 11
Key: i
Warning: Illegal string offset 'default' in D:\xampp\htdocs\deeleenrit\issue.php on line 12
Default: i
Warning: Illegal string offset 'extra' in D:\xampp\htdocs\deeleenrit\issue.php on line 13
Extra: i Column: 4
Warning: Illegal string offset 'type' in D:\xampp\htdocs\deeleenrit\issue.php on line 9
Type: i
Warning: Illegal string offset 'null' in D:\xampp\htdocs\deeleenrit\issue.php on line 10
Null? i
Warning: Illegal string offset 'key' in D:\xampp\htdocs\deeleenrit\issue.php on line 11
Key: i
Warning: Illegal string offset 'default' in D:\xampp\htdocs\deeleenrit\issue.php on line 12
Default: i
Warning: Illegal string offset 'extra' in D:\xampp\htdocs\deeleenrit\issue.php on line 13
Extra: i
</output>

**Comment by wfvdijk** [comment]
PHP Version 7.2.33
mysqlnd 5.0.12-dev - 20150407

**Comment by SergeyTsalkov** [comment]
Are you using the latest version of MeekroDB? Please grab the latest version to make sure.

**Comment by SergeyTsalkov** [comment]
In the older version of MeekroDB, `DB::columnList($table)` just returns a list of table names. You would use it like this:
```php
$columns = DB::columnList($table_name);
foreach ($columns as $column) {
  echo $column . "\n";
}
```

In the latest version, it returns an assoc array with more detailed information.

It looks like you might be using an old version, but reading the latest documentation?

**Comment by wfvdijk** [comment]
although I had a recent version the latest download from github fixed the problem
