### ISSUE TITLE
queryWalk in queryWalk?

### ISSUE THREAD

**Issue by nexoos-team** [SergeyTsalkov/meekrodb#74]
What to do when you need to execute another big request inside one large request?
I get Uncaught MeekroDBException: Commands out of sync; you can't run this command now.

**Comment by SergeyTsalkov** [comment]
queryWalk() uses a MySQL feature that avoids reading the entire result set into memory, but the price for that is that you can't run another query on the same connection until you've retrieved the entire result set from the first query. The only option is to use MeekroDB's object oriented mode and open up 2 database connections at once.

**Comment by nexoos-team** [comment]
Version 2.3
could do ** DB :: queryRaw **
then in the ** while ** loop make additional queries like
`DB :: queryFirstRow ('SELECT * FROM'. TABLE_MANUFACTURERS. 'WHERE manufacturers_id =% i', $ manufacturers_id);`
or the same ** DB :: queryRaw **
And then turn on debug mode and see the requests, their execution time, etc.
What is the correct way to use meekrodb 2.4 then in these cases?

**Comment by SergeyTsalkov** [comment]
First, I'd encourage you to just use DB::query() for your big query and see if it works. If you have enough memory, you'll be fine and you won't need queryWalk().

If you run out of memory trying to use DB::query(), then you should use queryWalk(). In that case, you'll need to use MeekroDB's object oriented mode to open up 2 separate database connections. Use the first connection for the queryWalk() and the second connection for the repeated queryFirstRow(). See: https://meekro.com/docs/static-vs-object.html

**Comment by nexoos-team** [comment]
DB::query() использовать не получается потому что логика всего приложения построена на циклах while, для лучшей производительности чтоб не делать сначала большой foreach в DB::query(), а потом еще один после.

По хорошему в meekrodb нужна еще одна функция которая выполняется максимально нативно, с использованием подстановочных параметров и хуков.

Попробую привести пример

$configuration_query = DB::queryFast('SELECT * FROM ' . TABLE_CONFIGURATION);

while ($configuration = mysqli_fetch_assoc($configuration_query)) {
    ...
}

а в DB::queryFast(){
обработка переданных параметров 
обработка хуков
и return $result = $db->query($query);
}

**Comment by nexoos-team** [comment]
Посмотрел код, нашел там
`$is_buffered = !($opts_raw || $opts_walk);`
Если ее заменить на
`$is_buffered = !($opts_walk);`

То будет работать.

Еще за место 

```
$Walk = DB::queryWalk("SELECT * FROM bigtable");
while ($row = $Walk->next()) {
    var_dump($row); // assoc array for one row
}
```

я предлагаю использовать

$Walk = DB::queryWalk("SELECT * FROM bigtable", function ($data) {
	echo $data["name"];
});

т.е. к каждому результату выполнить функцию и мы однозначно пройдем по всем  результатам
и в queryWalk следить за $Walk->free();

**Comment by SergeyTsalkov** [comment]
Here is the rationale for how it works: the whole point of queryRaw() and queryWalk() is that you don't read the entire result set into memory. If $is_buffered is true, the mysqli driver reads the entire result set into its own memory as soon as the query is run -- look up the documentation on MYSQLI_STORE_RESULT if you don't believe me.

Therefore, queryRaw() and queryWalk() must use $is_buffered=false, otherwise they are pointless.

Again, my suggestion for your situation is this: either use DB::query() instead of queryWalk(), or use 2 database connections with separate instances of MeekroDB. The first connection can run the queryWalk() while the second connection does everything else, like this:

```php
$db1 = new MeekroDB();
$db2 = new MeekroDB();
$Walk = $db1->queryWalk(...);
while ($row = $Walk->next()) {
  $db2->queryFirstRow('SELECT * FROM'. TABLE_MANUFACTURERS. 'WHERE manufacturers_id = %i', $manufacturers_id);
}
```

**Comment by nexoos-team** [comment]
я вас понимаю, может тогда оставить queryRaw  и сделать для него 
`$ is_buffered = true`
а queryWalk использовать уже с 
`$is_buffered=false`

Смысл в queryRaw  не перебирать несколько раз массив результатов.

**Comment by SergeyTsalkov** [comment]
Since queryRaw() is considered deprecated, I am willing to make that change.

See https://github.com/SergeyTsalkov/meekrodb/commit/7febdbd1f5fd69655d942979473176eea7bb1b9f

**Comment by nexoos-team** [comment]
Thank you!
