### ISSUE TITLE
Добавить функцию queryFirstFieldAsKey

### ISSUE THREAD

**Issue by nexoos-team** [SergeyTsalkov/meekrodb#80]
Пример:

\DB::queryFirstFieldAsKey('SELECT **code**, languages_id FROM ' . TABLE_LANGUAGES);

```
Array
(
    [ru] => Array
        (
            [code] => ru
            [languages_id] => 1
        )

    [uk] => Array
        (
            [code] => uk
            [languages_id] => 5
        )

    [en] => Array
        (
            [code] => en
            [languages_id] => 6
        )

)
```

**Comment by SergeyTsalkov** [comment]
I don't understand your request, could you please explain more clearly and write in English?

**Comment by nexoos-team** [comment]
Often there is a need to get an array where the keys are the values of the first column in the query.
in the example above it is **code**
And so not to do at first DB::query(select);
and then it goes through the loop and forms a new array, I propose to make an additional function.

**Comment by SergeyTsalkov** [comment]
I understand what you're doing now, but this is obscure enough that I'm not going to add it to the main library. You can do it pretty easily by adding your own custom function, though.
