### ISSUE TITLE
Supporting reconnection after wait_timeout passed

### ISSUE THREAD

**Issue by wadih** [SergeyTsalkov/meekrodb#88]
When wait_timeout is passed, the server cuts the connection, and we get the standard mysql error at the next query: 

"MySQL server has gone away" 

To reproduce, we can do: 

```
DB::query("SET SESSION wait_timeout=1");
sleep (2);
DB::query("select 1");
```

I'm looking in the existing code to see if I can detect that the connection is not good anymore and handle it before the next query.

I tried calling DB::getMDB(); after timeout has passed, but the internal state still thinks connection is active, until I try a query, then it dies. 

Is there a way to proactively catch that scenario? Or do we have to do a try and catch? 

Maybe we could have an auto reconnect feature in Meekro? One way I can think of implementing it is by moving the try and catch inside Meekro to detect "server has gone away" error to attempt to reconnect once, and if it fails again, then simply go on with the exception. Just food for though, what do you think? 

Here's what I have so far: 

```
DB::query("SET SESSION wait_timeout=1");

sleep(2);

try {
    DB::query("select 1");

} catch (Exception $e) {

    if ($e->getCode() == 2006) {

        DB::disconnect();

        print_r(DB::query("select 1"));

    }

}
```

That works and successfully restores the connection.

I was wondering if there is another way we can catch proactively that the connection has timed out, so I can simply do this, and avoid the try and catch statement: 

```
if (timed_out_condition){
  DB::disconnect();
}
```

My use case is that I have a little php daemon that runs on the long term and sporadically does inserts on a table. By default, mysql wait_timeout is 28800, 8hrs. So the connection cuts overnight, and I get the error the next morning.

**Comment by SergeyTsalkov** [comment]
Fixing this in the meekrodb library is a good idea. Using mysqli.reconnect used to be the solution to this, but it doesn't work with more modern versions of PHP that have switched from libmysql to mysqlnd as the driver used under the hood.

Anyway, there are two options for fixing this in meekrodb: First, I could automatically catch the 2006 error code and retry the query. Second, I could keep track of how long it's been since we ran our last command. If it's been too long, do a reconnect before attempting the query.

In the meantime, you could fix this for yourself by doing a reconnect every time your php daemon wakes up from a long sleep. For example:
```php
while (true) {
  sleep($a_long_time);
  DB::disconnect(); // we just woke up, maybe the connection is no longer good?
  DB::query("..."); // whatever we woke up to do

  // we're done now, back to sleep!
}
```

**Comment by wadih** [comment]
Sounds good.

I'm comfortable with the `DB::disconnect();` solution, as it keeps the layers of abstraction minimal, and I know nothing too complicated is happening under the hood. 

I think if we go ahead with a solution, it should be as simple as possible. I would opt for the first version, of catching 2006 when it happens.

Let's say we catch 2006, then how many times should we re-try the connection? I would say just once. If it needed 2 or more attempts to work again, it's not clean, it shouldn't be considered as "working", it should throw an exception and advise the developer. I wonder how mysqli.reconnect was trying to handle it. 

I wonder if the lib developers had given up on "reconnect" because it was never reliable, so they decided to let users control the lifecycle? I couldn't say. 

In any case, if meekro starts monitoring that on our behalf, perhaps it should be controllable with a variable, e.g. `DB::$reconnect_on_error_2006 = true;`, and it's behavior should be predictable, e.g. only re-try once after 2006 error.

I think it's good that not too many things happen under the hood, we can stay close to the lifecycle!

I think we can consider the issue resolved for now! Thank you so much.

Should close the case here?

**Comment by SergeyTsalkov** [comment]
The reason mysqli.reconnect got dropped is that it can break things. Keep in mind that disconnects can happen for reasons other than timeout, especially if you're talking to a remote mysql server over the internet. If you're using transactions or session variables, a reconnect will leave you in a bad state. You can have an internet connection drop in the middle of a transaction, the library re-connects, and your code keeps going, totally unaware that you're no longer in the transaction.

Maybe it would make more sense for meekrodb to do timer-based reconnects internally. That way we only reconnect when the connection has been idle for longer than $wait_timeout. It would prevent us from reconnecting in the case of randomly dropped connections, possibly screwing up people's transactions.

I'll leave this open to remind me to add this feature to meekrodb.

**Comment by SergeyTsalkov** [comment]
I added a `$reconnect_after` variable. If it's been at least this many seconds since the last query, it will reconnect before running another query. The default is 4 hours, which is half of MySQL's default `wait_timeout`. If you changed `wait_timeout` in your MySQL config, you should set `$reconnect_after` to half of that (just to be safe).

This is the cleanest solution, in my opinion.
