### ISSUE TITLE
Might be a bug handling columns with a dot in the name at least for Insert() and InsertUpdate()

### ISSUE THREAD

**Issue by wadih** [SergeyTsalkov/meekrodb#90]
Hi Sergey,

Hope all is well. 

I think there might be a bug with handling of columns that include dots inside the column name, at least for Insert() and InsertUpdate(). 

This call: 

    DB::update('MyTable', ['column.testing' => 1],"1=1");

Gives the following error:

    Uncaught MeekroDBException: Unknown column 'column.testing' in 'field list' in

What I found troubleshooting it is that it is trying to execute statement:

    update MyTable set `column`.`testing` = 1 where 1=1;

While it should have produced:

    update MyTable set `column.testing` = 1 where 1=1;

This happens even if I pass the backticked column name, e.g.:

    DB::update('MyTable', ['`column.testing`' => 1],"1=1");

I found it's happening in `parse()` for the argument type `%lb` which is handled by `formatTableName()`, that's the part that transformed `column.testing` to `column`.`testing` 

While debugging `formatTableName()` I noticed on line 380 strpos() can return both 0 (string found at position 0) and false (string not found) , just not sure if it opens the door to possible issues if it's evaluated as `if (strpos())` rather than `if (strpos() !== false)` or  `if (is_numeric(strpos()))`. It seems it might return unexpected behavior for columns that start with a dot, and where the dot position is at 0, which appears to be acceptable my mariadb, e.g. column called `.columnname` .

**Comment by SergeyTsalkov** [comment]
Thanks for this report! The problem is that we're using the same function to quote both table names and column names, and we shouldn't be. The split-on-dot thing shouldn't be happening for column names.

I'll have a fix pushed, hopefully in the next few minutes. Could you please confirm that it resolves the problem for you?

**Comment by wadih** [comment]
Hi Sergey!

Wow that was fast!

Tested it and works great. Thanks so much!
