### ISSUE TITLE
Meekrodb version 2.4 has issue with character encoding.

### ISSUE THREAD

**Issue by depdui** [SergeyTsalkov/meekrodb#93]
file db.class.php
Line 284: $query = preg_replace('/[\x00-\x1F\x7F-\xFF]/', '', $query);
this line of code replaced our vietnamese query characters.

I would like to know the main purpose of this line of code.
Temporarily, I had comment this for my project.

Thanks and best regards,

Zhang Khoa

**Comment by SergeyTsalkov** [comment]
The test suite still passes without this line, I'll go ahead and remove it. I'm not sure anymore what it was there for.
