### ISSUE TITLE
Insert raw binary data into TEXT column causes "Incorrect string value" error. Why?

### ISSUE THREAD

**Issue by sonqor** [SergeyTsalkov/meekrodb#95]
I created a MySQL table with `(CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci)`:
`CREATE TABLE my_tab (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
my_col TEXT DEFAULT NULL
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;`

Initialized MeekroDB:
`DB::$user = $username;
DB::$password = $password;
DB::$dbName = $name;
DB::$encoding = 'utf8mb4';`

Then tried to insert binary data:
`try {
    DB::insert('my_tab', [
      'my_col' => openssl_random_pseudo_bytes(16)
    ]);
} catch(Exception $e) {
  echo "Error: " . $e;
}`

Contrary to my expectation, MeekroDB didn't escaped the characters and fatal error happened:
`Error: mysqli_sql_exception: Incorrect string value: '\x975\xD1\x87\xFF\x14...' for column`

**I need to remind you of two points:**
1. I don't want to store binary data in BLOB column data type (TEXT preferred).
2. I don't want to encode the binary data generated by `openssl_random_pseudo_bytes(16)` before inserting into the column (e.g. by using `bin2hex` or `base64_encode` functions)

I really expected this library to perform "Character Escaping" operations well, but I ran into a problem with this.

**Comment by SergeyTsalkov** [comment]
This is not a bug in the library. MySQL requires that TEXT types be used to store valid utf8 strings. BLOB is the appropriate data type to store binary data that does not correspond to valid utf8 strings.
