### ISSUE TITLE
DB::queryFirstRow returning null when direct command show records

### ISSUE THREAD

**Issue by Dinosane2** [SergeyTsalkov/meekrodb#97]
After this simple command

        $id = DB::queryFirstRow("select id from produto where Descricao=%s",$nome);
        
$id is null

MySQL log shows that the proper query was executed. Running the very same query direct on database returns values.

**Comment by Nrde** [comment]
You could use $id = DB::queryFirstField("

Also you can debug the queries, i.e., DB::$logfile = '/home/username/querylog.txt'; to see what goes wrong.

Null means the query did not find anything.

**Comment by SergeyTsalkov** [comment]
Your command is valid. Maybe you're connecting to the wrong database? In any case, there's no bug here.

**Comment by Dinosane2** [comment]
I did this:

	SET global general_log = 1;
	SET global log_output = 'table';
	truncate mysql.general_log;
	select * from mysql.general_log;

So I could check inside mysql if the command was properly	run. I got the command as it was shown in mysql and run it directly against mysql. It works. So my conclusion was that "$id = DB::queryFirstRow" was running but not returning the received values.

I will check the debug log if I retrieve any more info.

**Comment by Dinosane2** [comment]
![image](https://github.com/SergeyTsalkov/meekrodb/assets/52465931/be90be23-0be7-4402-92ab-0f4f263ded6e)

The image above is conclusive. To consider:

- this is a debug screen (phpstorm)
- the first query "DB::query" returns values as you can see in the watch area bellow
- the same query "DB::queryFirstRow" returns null
- the table has only one record, as the first query is shown
