### ISSUE TITLE
PHP 8+ support

### ISSUE THREAD

**Issue by diltiwari** [SergeyTsalkov/meekrodb#98]
Hi,
Its not working with PHP 8+ versions.
Do we get an upgrade in future ?

Thanks

**Comment by SergeyTsalkov** [comment]
I thought I tested with PHP 8. Could you give a specific example, and the error you get?

**Comment by diltiwari** [comment]
My apology. 
Its working and I tested with PHP 8.1.
There was some conf issues at my end.
Thank you very much.
